events {
    worker_connections 1024;
}

http {
    upstream flask_app {
        # Configuración de balanceo de carga por pesos:
        # app1 (peso 3): alta capacidad
        # app2 (peso 2): capacidad media
        # app3 (peso 1): capacidad baja
        server app1:5001 weight=3;
        server app2:5002 weight=2;
        server app3:5003 weight=1;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
